#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: webhook-receiver
#  namespace: flux-system
#  annotations:
#    "cert-manager.io/cluster-issuer": letsencrypt
#spec:
#  tls:
#    - hosts:
#        - flux-webhook.example.com
#      secretName: flux-webhook-tls
#  rules:
#  - host: flux-webhook.example.com
#    http:
#      paths:
#      - pathType: Prefix
#        path: /
#        backend:
#          service:
#            name: webhook-receiver
#            port:
#              number: 80
