# https://metallb.universe.tf/installation/#installation-with-helm
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: "0.10.2"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    configInline:
      address-pools:
        - name: ingress-gateway
          protocol: layer2
          addresses:
            - 10.0.1.1/32
        - name: default
          protocol: layer2
          addresses:
            - 10.0.1.128/25
