# Chart values: https://github.com/coredns/helm/tree/master/charts/coredns
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
spec:
  releaseName: coredns
  chart:
    spec:
      chart: coredns
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
      version: "1.16.3"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    deployment:
      name: "coredns"
    service:
      clusterIP: "10.43.0.10"
      name: "kube-dns"
    servers:
      - zones:
          - zone: .
        port: 53
        plugins:
          - name: errors
          # Serves a /health endpoint on :8080, required for livenessProbe
          - name: health
            configBlock: |-
              lameduck 5s
          # Serves a /ready endpoint on :8181, required for readinessProbe
          - name: ready
          # Required to query kubernetes API for data
          - name: kubernetes
            parameters: cluster.local in-addr.arpa ip6.arpa
            configBlock: |-
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
          - name: hosts
            parameters: /etc/coredns/NodeHosts
            configBlock: |-
              ttl 60
              reload 15s
              fallthrough
          # Serves a /metrics endpoint on :9153, required for serviceMonitor
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . 10.0.0.1
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
